# Generated by Django 2.1.1 on 2018-10-11 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='模块名称')),
                ('desc', models.CharField(blank=True, max_length=5000, verbose_name='模块描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='项目名称')),
                ('desc', models.CharField(blank=True, max_length=5000, verbose_name='项目描述')),
                ('status', models.BooleanField(default=0, verbose_name='项目状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='module_info',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='module_info',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='project_info',
            name='create_user',
        ),
        migrations.DeleteModel(
            name='module_info',
        ),
        migrations.DeleteModel(
            name='project_info',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='module',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.Project'),
        ),
    ]
